import { listPublicBusinessGuides } from "@/lib/db";
import Link from "next/link";
import { MoveRight } from "lucide-react";
import { EditorialPageIntro } from "@/components/EditorialPageIntro";
import type { Metadata } from "next";

export const revalidate = 60;
export const metadata: Metadata = { title: "Garment Sourcing Guides & Industry Insights | Himat Textile", description: "Access editorial guides and B2B apparel industry insights on starting a garment brand, wholesale buying patterns, and catalog sourcing logistics." };

export default async function BusinessGuidePage() {
  const guides = await listPublicBusinessGuides();
  return <div className="min-h-screen bg-[#161612] text-[#F4EFE6]"><main>
    <EditorialPageIntro eyebrow="06 / Business Guide" title={<>Your garment<br /><span className="text-transparent stroke-text">guide in</span><br />Ahmedabad.</>} description="Buying garments is not only about finding products. It is about finding the right products, the right quantities and the right price for your market." image="https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=1400" imageAlt="Textile sourcing consultation" ctaLabel="Talk to our garment team" ctaHref="/#enquiry" />
    <section className="paper-surface border-t border-[#161612]/10 px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-6 border-b border-[#161612]/15 pb-7 lg:flex-row lg:items-end"><div><span className="mono-label text-[10px] text-[#C95A1A]">Product selection / stock planning / market guidance</span><div className="accent-rule mt-5" /><h2 className="mt-7 font-display text-4xl font-black uppercase leading-[.86] tracking-[-.08em] sm:text-7xl">Make smarter<br />buying decisions.</h2></div><p className="max-w-md text-sm leading-relaxed text-[#161612]/65">Articles and resources for retailers, wholesalers, fashion brands and emerging labels navigating garment sourcing.</p></div>{guides.length === 0 ? <div className="py-16 text-center font-mono text-[10px] uppercase tracking-widest text-[#161612]/45">No guides found.</div> : <div className="mt-12 grid gap-px bg-[#161612]/15 sm:grid-cols-2">{guides.map((guide) => <article key={guide.id} className="group bg-[#F4EFE6] p-6 transition-colors hover:bg-[#E7E0D3] sm:p-8">{guide.coverImage && <div className="mb-7 aspect-video overflow-hidden bg-[#E7E0D3]"><img src={guide.coverImage} alt={guide.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /></div>}<span className="mono-label text-[9px] text-[#C95A1A]">Published article</span><h3 className="mt-3 font-display text-3xl font-black uppercase leading-[.9] tracking-[-.06em] text-[#161612]">{guide.title}</h3><p className="mt-4 line-clamp-3 text-sm leading-relaxed text-[#161612]/65">{guide.content}</p><div className="mt-8 flex items-center justify-between border-t border-[#161612]/15 pt-4"><span className="mono-label text-[9px] text-[#161612]/45">{guide.views} reads</span><Link href={`/guide/${guide.slug}`} className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#161612] transition-colors hover:text-[#C95A1A]">Read guide <MoveRight size={12} /></Link></div></article>)}</div>}</div></section>
  </main></div>;
}
